### ISSUE TITLE
Grid bleeds outside of viewport when drawn.

### ISSUE THREAD

**Issue by jceipek** [jceipek/Complete-Galactic-Dominion#1]
Not sure how best to fix this (and it isn't high priority right now), but the grid drawing method assumes that the viewport fills the screen, so it bleeds outside of the viewport.

**Comment by pvarin** [comment]
I don't think this is a problem. In fact we need to account for this bleeding anyway, because it may be necessary to draw objects that should only be partially on the screen.

**Comment by pvarin** [comment]
Never mind, I fixed it.

**Comment by jceipek** [comment]
Problem: now you can't draw the HUD - it will get clipped.

**Comment by pvarin** [comment]
Gah... Okay, well you create a viewport surface that can be clipped, and blit this surface to the displaySurface. I'm on it.

**Comment by jceipek** [comment]
Won't that be really slow? Then every unit and grid square needs to be blitted twice!

Remember that this is flagged as medium priority, and might not be necessary at all.

We might just be able to make the HUD such that it covers the bleeding...

**Comment by pvarin** [comment]
The HUD does not necessarily need to be re-drawn every time the Viewport surface needs to be redrawn. Because the HUD will be just as large or larger than the Viewport surface, it will take just as much time to redraw the HUD as it would to redraw the Viewport surface. So I don't think it will take any longer.

In fact, the blit to the displaySurface will be shorter than the blit to the viewportSurface, because the image has already been consolidated.

To be honest, I didn't see your post until after I had implemented this solution. We can always change it back.

**Comment by jceipek** [comment]
Not sure about that - the HUD will overlap the viewport in several areas - for example the resource bar on top.

Large blits are slow, and drawing the viewport will now mean drawing every unit and terrain object to the viewport surface and then blitting the viewport surface to the screen. We'll find out how fast/slow it is, I guess, and we can revert back later if needed.

Did you see my other issue comments?

**Comment by jkirschner** [comment]
We should separate the map (scrollable) and the HUD elements which go on top of it from the HUD below the map.  The HUD below the map is static, and should only be blitted over if it changes.  (If we are going to best efficiency, in my opinion.)

**Comment by jceipek** [comment]
http://cache.gawker.com/assets/images/9/2009/11/500x_custom_1258053414987_starcraft_brood_war.jpg

Note that the bottom HUD is not a rectangle.

**Comment by jceipek** [comment]
Also, the minimap updates constantly.

**Comment by jkirschner** [comment]
Right, I forgot that what is currently a rectangle may not always be (you don't have a transparent background).  And, yes, the minimap updates constantly.  But, if for some reason there is something that doesn't update constantly, we should not blit it.  This is only a concern if our implementation isn't fast enough though.

**Comment by jceipek** [comment]
Exactly.
