### ISSUE TITLE
Unable to exit fullscreen mode if exception occurs

### ISSUE THREAD

**Issue by jkirschner** [jceipek/Complete-Galactic-Dominion#12]
An error occurred when I right-clicked at a specific spot on the grid.  Normally this isn't an issue.  However, an exception was thrown, but the graphics display (FPS) continued to update.  Scrolling was no longer occurring, and no key presses (including ESC and CTRL+ATL+DELETE were working).  I had to restart my computer.

This is annoying and should be fixed.

**Comment by jceipek** [comment]
That is very odd. Maybe Patrick will know what to do - it has something to do with the threading implementation.

**Comment by jkirschner** [comment]
Fixed.  This will no longer happen, and we will even get the exception traceback still!

**Comment by jceipek** [comment]
Neat!
