### ISSUE TITLE
Entity information still shown after death

### ISSUE THREAD

**Issue by jkirschner** [jceipek/Complete-Galactic-Dominion#20]
I am not sure how this was implemented, but an entities information should no longer be shown after it does (or, at least that is my opinion).  Currently, the information stays up there with negative health.  @Berit, if you implemented this, could you fix it?

**Comment by jceipek** [comment]
2 things need to happen when a unit dies, before del is called:

selected property should be set to False
entity should be removed from selected entity list

**Comment by jkirschner** [comment]
Fixed.
