### ISSUE TITLE
Depositing Resources in Groups

### ISSUE THREAD

**Issue by jceipek** [jceipek/Complete-Galactic-Dominion#21]
Units cannot deposit resources if they have not all gathered resources, but only if they have not been re-selected. 

Steps to replicate:
1. Use a unit to gather most of the gold from a mine and deposit it in a building.
2. Select a group of units that have never gathered resources.
3. Gather the remaining gold in the mine with the group (some will not gather anything)
4a. Attempt to deposit - fail
4b. Attempt to gather gold from a different mine - fail

Deselecting and r

eselecting the group will allow (4) again.

**Comment by jkirschner** [comment]
Fixed.

There was a statement of the form list > len(list) somewhere, which obviously had inconsistent results.  It was changed to len(list) > len(list).
