### ISSUE TITLE
Scrolling world only on mousemove!

### ISSUE THREAD

**Issue by jceipek** [jceipek/Complete-Galactic-Dominion#3]
Method should actually set scroll speed and the viewport should only actually scroll the grid on update event.

**Comment by pvarin** [comment]
Which method are you talking about? Soooo many methods....

**Comment by pvarin** [comment]
I'm worried about how events are being used. Their original purpose was to manage user input: take key presses, mouse clicks and mouse motion and interpret them.

Anything else _should_ be able to be processed with function calls rather than the creation of events. How necessary are things like RefreshEvent and RefreshCompleteEvent? We could simply give the listeners the appropriate methods and call these methods at the appropriate times. Maybe I'm worrying too much, but I think that making an event for everything, like BuildEvent and BuildCompleteEvent will get us into trouble when we are trying to make the game deterministic...maybe? Sequentially processed code (series of function calls) is much more deterministic than parallel processed code (series of events).

**Comment by jceipek** [comment]
The parallel vs sequential issue needs to be handled by timestamps (think of what will happen when two messages sent by the server arrive out of order).

**Comment by jceipek** [comment]
I suggest you read through the interface implementation starting at client.py. Only the interface is a listener, and it uses method calls to address sub-objects.

**Comment by jceipek** [comment]
The method I was referring to is part of a chain starting with 

UserInterface.py
    def notify(self,event):
        if isinstance( event, Event.MouseMovedEvent ):
            self.activeScreen.processMouseMovedEvent(event)

and ending with

Viewport.py
    def scrollBasedOnMousePos(self,mousePos):

**Comment by pvarin** [comment]
Hmm... we can't give the frame rate to the MouseMovedEvent, because the frame rate needs to be given even if the mouse isn't moving. So the frame rate should be given as an attribute of some other event. The update event...maybe? (I'm not sure what the update event does.)

**Comment by jceipek** [comment]
Update event already has that; it just needs to be connected to scrolling, and scrolling needs to be done based on a scroll speed changed every mouse move.

```
from Event import Event

class UpdateEvent(Event):
    """
    Request to update objects.

    #Attributes:
    #   elapsedTime = time that has passed since the last frame. Used to sync 
                      movement speed across different hardware
    """

    def __init__(self,elapsedTime):
        Event.__init__(self)
        self.elapsedTime = elapsedTime
```

**Comment by pvarin** [comment]
What is it that creates update events?

**Comment by jceipek** [comment]
Window.py

```
def run(self):
    self.updateClock()

    self.pygameEventThread = threading.Thread(target=self.pygameEventPoster)
    self.pygameEventThread.setDaemon(True)
    self.pygameEventThread.start()

    while self.active:
        #Pass all pygame events to a parser thread for wrapping in standardized events
        #I DON'T KNOW IF THIS WILL WORK PROPERLY FOR MULTIPLE EVENTS, YET - Julian

        self.pygameEvents = pygame.event.get()

        #Tell the objects on screen to update. #HERE IT IS, PATRICK
        #NOTE: NOTHING INTERCEPTS THIS AT THE MOMENT
        self.manager.post(Event.UpdateEvent(self.gameFrametime))

        #Note: the renderer does not update or display anything.
        #It simply draws to the displaySurface i.e. self.displaySurface.fill((0,0,0))
        self.manager.post(Event.RenderEvent(self.displaySurface,self.resolution))

    pygame.quit()
```

**Comment by pvarin** [comment]
I have a solution, and it works locally but there are some serious merge conflict when I try to push.

Viewport should not have a mouse object. That makes no sense. It's already getting the mouse position through the mousemotion event, what else does it need?

**Comment by jceipek** [comment]
Viewport should not _have_ a mouse object. There should be a mouse object that listens for mouse events; it should be sent events by interface or should be an actual Listener that sends messages to the UserInterface (probably better).

The mouse object is needed for eventual double-click support.

**Comment by jceipek** [comment]
Why can't you pull and then fix the conflicts?

**Comment by pvarin** [comment]
okay, good. I was confused, because Viewport has a mouse right now...

Also, you should pull and see if the scrolling works for you.

**Comment by jceipek** [comment]
Nice new commit. Two notes:
1. Scrolling is no longer bidirectional even though it is biaxial.
2. scrollSpeed is supposed to be a user-adjustable value determining how sensitive the mouse is to distance from the deadZone edge.

**Comment by pvarin** [comment]
Ahh, okay...I noticed the scrolling problem. I can fix that. It was code that was used in the previous implementation so I didn't want to mess with it at the time.

So does mouse have a scrollSpeed attribute (I called it scrollFactor in the new commit, I think I'll call it scrollSensitivity)?

**Comment by jceipek** [comment]
It should be called scrollSensitivity, and I didn't make the mouse object, so I don't know.

The current commit has disabled scrolling completely, in case you were unaware of that.

Just an observation, the following:
    self.mouseDownButton
will not work because it is possible for someone to press two or more mouse buttons at the same time.

**Comment by jkirschner** [comment]
Julian,

While true, if someone right-clicks, then left-clicks before releasing the right-click, we would expect the user to have changed his/her mind about which button they wanted to click.  If this assumption is wrong, then, yes, that will not work in all cases.  I can fix it if need be.

**Comment by jceipek** [comment]
Not sure - my only RTSes are on PCs, so I can't test that right now. See if anyone nearby has Starcraft or AoE.
